### ISSUE TITLE
Image always nil

### ISSUE THREAD

**Issue by dewsy** [mmcdole/gofeed#133]
### Expected behavior
Item.Image returns string

### Actual behavior
Item.Image is nil

### Steps to reproduce the behavior
I tried ~2000 articles from 279 different RSS feeds (all of them were XML) and all of the 2000 goffed.Item had nil for image. I looked at the XML feeds, there were image links in them. It must be a parsing errror.

**Comment by sudhanshuraheja** [comment]
@dewsy could you share links to a few RSS feeds where you were unable to get this to work?

**Comment by arrow-dev** [comment]
Similar problem here,

https://businessdesk.co.nz/feed

Not getting any image data and also another problem I'm seeing with this feed is I get a strange value for Author like this:

author: {
  email: "<name>Some Name</name><email>SomeEmail</email>"
}

**Comment by sudhanshuraheja** [comment]
Thanks @arrow-dev will try it out this weekend.

**Comment by sudhanshuraheja** [comment]
So, there are two issues here.

### Author
The author doesn't get parsed properly because the RSS spec expects
`<author>lawyer@boyer.net (Lawyer Boyer)</author>`

but the XML contains
```txt
<author>
    <name>Howard</name>
    <email>the_actual_email@site.com</email>
</author>
```

### Image Data
I can see an image tag inside items, like so
```txt
<image>
    <url>https://media.businessdesk.co.nz/file/c_fill,w_330/Invercargill-Dee-St.jpg</url>
    <title>Tiwai closure: Southlanders look for options</title>
    <link>https://businessdesk.co.nz/article/tiwai-closure-southlanders-look-for-options</link>
</image>
```

Though, what I find strange is that the [RSS spec](https://validator.w3.org/feed/docs/rss2.html#ltimagegtSubelementOfLtchannelgt) doesn't have image as a tag inside items

I believe this is why, the default mappings for `gofeed.Item` uses only the following for Rss `/rss/channel/item/itunes:image` and `/rss/channel/item/media:image` and none for Atom.

### Possible Solutions
Overall, I'm not sure about raising a PR for parsing elements that are not in the spec. Here's the documentation about using a [custom parser](https://github.com/mmcdole/gofeed#advanced-usage)

**Comment by arrow-dev** [comment]
@sudhanshuraheja Thanks for that info, first time dealing with RSS. With the Author it looked like it was lining up with the struct in GoFeed and the same with Image. Looks like this feed is not correctly formatted to the spec and I will need to do a custom parser. - I agree there would be no need for a PR to parse elements not in the spec.

**Comment by prologic** [comment]
@arrow-dev Did you end up writing a custom parser? I too would like to be able to extract images from various RSS/Atom feeds for https://feeds.twtxt.net/ (_sigh no one follows the spec!_)

**Comment by arrow-dev** [comment]
@prologic Actually just ended up using the standard library as shown [here](https://godoc.org/encoding/xml#example-Unmarshal)

**Comment by prologic** [comment]
> @prologic Actually just ended up using the standard library as shown [here](https://godoc.org/encoding/xml#example-Unmarshal)

Can you share your code? I don't really feel like reinventing Atom/RSS parsing for what amounts to similar problems you had with gofeed :)

**Comment by arrow-dev** [comment]
@prologic I'm not able to share the code but basically it is exactly like in that linked example from godoc,


- define type(s)/struct(s) reflecting the fields that you want to pull out, in the same shape as the feed/xml with meta tags to map the xml field names and/or attributes

- instantiate a variable with the empty/default value of that struct

- call xml.Unmarshal(<xml feed as bytes>, <pointer to the var to populate with data>) and you should end up with the  struct being populated

**Comment by infogulch** [comment]
It seems images are all over the place. I'm seeing:

* extensions.media.content where attrs.medium = 'image' or attrs.type = 'image/*', then return attrs.url ([gmail blog](https://feeds.feedburner.com/OfficialGmailBlog), [xkcd](https://blog.xkcd.com/feed/))
* enclosures where type = 'image/*', then return url ([androidpolice](https://feeds.feedburner.com/AndroidPolice))
* the only image is the first `<img>` in content. ([Ars](http://feeds.arstechnica.com/arstechnica/index/), [fivethirtyeight]
(https://fivethirtyeight.com/politics/feed/), [marco.org](https://marco.org/rss))
* the only image is the first `<img>` in description

Would gofeed devs accept a patch that does a best-effort search in these locations (others?) to fill in the Image field? Any arbitrary search order is ok with me, it would just be nice to have *any* preview thumbnail for a [bare bones rss reader](https://github.com/infogulch/xrss) that I'm building without having to break out the parsers and query engines.

**Comment by rbren** [comment]
+1 to this--nytimes uses `media:content medium=image`. I'm parsing a bunch of different major news sources, and none get images set.

Would love to get some more best-effort in for getting images.

(PS as someone who maintains an [RSS parser in JS](https://github.com/rbren/rss-parser), I know it's a slog. Thanks for the hard work here)

**Comment by rbren** [comment]
Here's a workaround that seems to capture most images:
```go
func getImageFromExtensions(item gofeed.Item) string {
    if media, ok := item.Extensions["media"]; ok {
        if content, ok := media["content"]; ok {
            for _, c := range content {
                if strings.Contains(c.Attrs["type"], "image") || strings.Contains(c.Attrs["medium"], "image") {
                    return c.Attrs["url"]
                }
            }
        }
    }
    return ""
}
```

**Comment by mmcdole** [comment]
> +1 to this--nytimes uses `media:content medium=image`. I'm parsing a bunch of different major news sources, and none get images set.
> 
> Would love to get some more best-effort in for getting images.

I agree.

Some of the existing "best-effort" code, which extracts data from extensions, is in the [translator file](https://github.com/mmcdole/gofeed/blob/master/translator.go) if you look at the `DefaultRSSTranslator`. This file converts the RSS object to the unified gofeed format.  You can see that we pull some fields out of the iTunesExt object, etc. This approach is convenient because it ensures that the RSS feed and item content are fully parsed before digging into them for various fields in different locations.

The question is whether we should add this functionality there, or modify `rss/parser.go` to perform best-effort image parsing, even when using the RSS parser directly, instead of the universal gofeed parser.

I learn towards leaving the RSS / Atom / other parsers as parsing the "raw" feed exactly as it is represented, and the gofeed has some quality of life features like best-effort parsing of various deeply nested fields, but I'm not totally sure. 

Any thoughts @rbren ?

**Comment by mmcdole** [comment]
@infogulch if the offer is still on the table, I'd accept a PR that covers the various use-cases you covered in `DefaultRSSTranslator`.  It looks like @rbren's code above covers some but not all of them that you mentioned.

If not, I can take a look at this -- it just will take a bit longer.

**Comment by superb-owl** [comment]
> I was leaning towards keeping the RSS / Atom / other parsers focused on parsing the "raw" feed exactly as it is represented, while the gofeed + translator handles some quality of life features like best-effort parsing of various deeply nested fields.

This sounds like a great strategy

**Comment by sudhanshuraheja** [comment]
Agree on it being the right strategy

**Comment by infogulch** [comment]
Oh it is! That could make it a bit easier.

**Comment by infogulch** [comment]
I opened a PR (above) to fix this.

Thoughts?

**Comment by mmcdole** [comment]
Looks great, thank you for the contribution !
