### ISSUE TITLE
Parse http://eatcodeplay.com/feed.xml

### ISSUE THREAD

**Issue by mmcdole** [mmcdole/gofeed#50]
This malformed feed has a self-closing feed tag at the beginning of it.  Need to iterate through other sibling elements if the first element is empty?

**Comment by Cj-Malone** [comment]
I don't think you should parse this feed. Feed requires certain children and the first tag doesn't so it's against spec, and an error should be returned.

Interestingly though I'm not sure if the spec allows multiple feed tags in a single file. The [spec](https://tools.ietf.org/html/rfc4287#section-2) explicitly says that an Atom Entry Document can only have one Entry tag, but it less direct about Atom Feed Document. Common since would say only one root tag, so I think being strict and returning an error or flexible and returning the first feed parsed is the best thing to do there.

**Comment by mmcdole** [comment]
@Cj-Malone I've been trying to balance being pragmatic about parsing out of spec feeds.  However, I think you are right in this case, this feed probably should fail and the accommodations for this specific broken feed aren't worth the increased complexity.  

Thanks for your comment!
