### ISSUE TITLE
Numerical character references are not decoded in text elements

### ISSUE THREAD

**Issue by galdor** [mmcdole/gofeed#64]
### Expected behavior
Feeds are XML documents. Character data can contains both predefined entites (such as `&lt;`) and numerical character references (e.g. `&#34;`). These references must be decoded; for example, `&#34;` has to be decoded to `"`. `encoding/xml` does it properly.

### Actual behavior
Gofeed decodes predefined entities (`internal/shared/parseutils.go`: `DecodeEntities`) but ignores numerical character references. Lots of feeds include html data which are encoded since they are included in a XML document. For example, feed generators often encode `"` with `&#34;` instead of `&quot;`.

### Steps to reproduce the behavior

```go
package main

import (
        "fmt"
        "log"

        "github.com/mmcdole/gofeed"
)

func main() {
        feedData :=
                `<?xml version="1.0" ?>
                 <rss version="2.0">
                   <channel>
                     <item>
                       <title>Test</title>
                       <description>&lt;a&gt; &#34;b&#34; &quot;c&quot;</description>
                     </item>
                   </channel>
                 </rss>`

        fp := gofeed.NewParser()
        feed, err := fp.ParseString(feedData)
        if err != nil {
                log.Fatalf("cannot parse feed: %v", err)
        }

        fmt.Printf("%s\n", feed.Items[0].Description)
}
```

This prints `<a> &#34;b&#34; "c"` instead of `<a> "b" "c"`.

**Comment by galdor** [comment]
For you information, numerical character references are decoded by `encoding/xml` starting at line 991 of https://golang.org/src/encoding/xml/xml.go.

**Comment by mmcdole** [comment]
@galdor thanks for the bug report.

For a number of reasons I was unable to utilize go's built in xml chardata decoding.  Mostly because I wanted to be able to parse naked XML/HTML for certain elements.  This has me using the `,innerxml` attribute which bypasses the built-in code you referenced.

So, I think to do this correctly, I'm going to have to re-implement what they do myself.  I'll have to replace the `string.Replace` code that I use in `parseutils.go` with a proper parser which decodes both the numeric and non-numeric character entities it finds in the text.

I'm currently in the process of rewriting my unit tests for this project (due to an unintentional licensing violation on my part).  When #53 is ready to merge with my completed Atom tests, I'll add some new unit tests for both atom/rss that ensures that character entities and numeric character entities get decoded correctly.

**Comment by galdor** [comment]
So there's only `DecodeEntities` to modify, i.e. parse the string to decode both types of entities ? I could give it a try if you wish.

**Comment by mmcdole** [comment]
@galdor sure, give it a try. 

I had considered implementing it like I did the other entity decoding, but I was concerned if there was a lot of the numeric entities that we would have to match, it may be an expensive operation to `strings.Replace` for so many items.

But, perhaps doing it the slow way is better than nothing for now, and I can take time to implement it on a character-by-charcter basis (like go's xml package does) later when I have time.

**Comment by galdor** [comment]
I should have a patch for you tomorrow.
