### ISSUE TITLE
item.PublishedParsed and *time.Time

### ISSUE THREAD

**Issue by jhautefeuille** [mmcdole/gofeed#73]
When I try to use item.PublishedParsed in goroutine, error occurs like

`panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x69193e]
`
item.PublishedParsed is a *time.Time type.

But on official golang doc https://golang.org/pkg/time/#Time, it should be time.Time

> Programs using times should typically store and pass them as values, not pointers. That is, time variables and struct fields should be of type time.Time, not *time.Time. A Time value can be used by multiple goroutines simultaneously. 

Is my problem relative to this ?

Thank you

**Comment by mmcdole** [comment]
This [SO question and answer](http://stackoverflow.com/questions/22074077/time-time-pointer-or-value), with comments, goes over why one would want to store time.Time as a pointer.

This [go-nuts](https://groups.google.com/forum/#!topic/golang-nuts/eRMeLv1_IXc) thread covers the same ground.

In short, I want to be able to JSON encode the Feed and Item types, and I want them to omit nil Time entries.  This isn't possible without making time.Time a pointer, or writing a custom marshaller.  

I do not think your issue is directly related to this.  

Can you post a minimal example that exhibits the behavior above?  I can probably help you sort it out.

**Comment by jhautefeuille** [comment]
Sorry for the delay in my reply.

You are absolutely right.

In fact, having read the articles of your links, I understood my mistake.

The principle of the program: I read a text file, for each url, I run a goroutine. Each goroutine parses the flow and sends the result into a channel.

My error was that after retrieving item.PublishedParsed, I would convert it to a string before applying Format (). But itemPublishedParsed is of type * time.Time. I also forgot to test the presence of the date before applying Format () so the error was thrown.

Thank you for your help that allowed me to find my silly mistake.

Thank you again for your library.

I close the ticket.
