### ISSUE TITLE
failure to parse categories from RSS (?) doc

### ISSUE THREAD

**Issue by armhold** [mmcdole/gofeed#85]
### Expected behavior

I expect feed.Categories to be `["News &amp; Politics"]`.

### Actual behavior

feed.Categories is: `[Jon Favreau POTUS Donald Trump politics Tommy Vietor Dan Pfeiffer Jon Lovett Pod Save America News & Politics]`.

### Steps to reproduce the behavior

Please see unit test here: https://gist.github.com/armhold/96be9635883fd417b6cb82ab445abddd

This feed comes from: http://feeds.feedburner.com/pod-save-america.

I haven't really dug into the code yet, so it's possible I'm doing something dumb here. But I think gofeed is accidentally adding the next line of the xml to feed.Categories.

**Comment by mmcdole** [comment]
I think this is expected behavior. 

If you take a look here:
https://github.com/mmcdole/gofeed/blob/master/translator.go#L211

Feed.Categories comes from:

```
rss.Categories  
rss.iTunesExt.Categories  
rss.DublinCoreExt.Subject  
```

These are all appended together into the same Feed "Categories" slice.  

You have two options here if you don't want this behavior.  

1. [You can write a custom translator very easily](https://github.com/mmcdole/gofeed#parse-a-feed-while-using-a-custom-translator) that _only_ uses rss.Categories when translating between rss.Feed->gofeed.Feed model.  See 
2. If you only need to parse RSS feeds and never Atom feeds, [you can use the RSS parser directly](https://github.com/mmcdole/gofeed#parse-a-rss-feed-into-a-rssfeed).  When you access the rss.Categories field, it will _only_ contain the straight RSS categories, not the iTunes or DublinCore extensions as well.

**Comment by armhold** [comment]
Ah, I get it, thanks. My programmer sense was that there was an off-by-one error in parsing the input. But I failed to take into account that gofeed.Feed is an amalgamation of the different feed types.

Sorry for the noise, and thanks for writing gofeed.
